name: blindness_detection
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.8
  - pip
  - pip:
    - numpy
    - pandas
    - sklearn
    - mlflow
    - pillow
    - argparse
    - dvc
    - tensorflow
